spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Hospital
    username: root
    password: 2004
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect